sudo: required

language: java

jdk:
  - oraclejdk8

services:
  - docker

jobs:
  include:
    - stage: build_jar
      script:
        - gradle build
    -stage: craate_and_push_docker_image
      script:
        - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
        - docker build -t $DOCKER_USERNAME/sql-mongo-client:latest .
        - docker push $DOCKER_USERNAME/sql-mongo-client:latest