language: java

jdk:
  - oraclejdk8

services:
  - docker

cache:
  directories:
  - $HOME/.m2

script:
  - ./gradlew build
  - docker build -t $DOCKER_USERNAME/sql-mongo-client:latest .
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker push $DOCKER_USERNAME/sql-mongo-client:latest